### ISSUE TITLE
[Bug] invisible Buttons

### ISSUE THREAD

**Issue by mofoni** [danzilberdan/obsidian-mathlive#2]
Hi,

first of all, great idea with the Plugin, this is something i have been searching for a while now.

Maybe this is already known, but there seems to be a problem with some of the Buttons on the keyboard being invisible.
They still work if you press them.

I installed only this Plugin in a brand new Vault to eliminate possible conflicts with other Plugins.

![image](https://github.com/danzilberdan/obsidian-mathlive/assets/96438242/ca24e4b5-a44f-4eb0-bc2e-8e57d83bde2f)
![image](https://github.com/danzilberdan/obsidian-mathlive/assets/96438242/2bb16347-7c30-445a-9f93-ed1567a13616)
![image](https://github.com/danzilberdan/obsidian-mathlive/assets/96438242/acd1644f-3b29-4157-a4f9-5d95b911adb6)
![image](https://github.com/danzilberdan/obsidian-mathlive/assets/96438242/1df58c2a-77c2-4c66-8951-fd9d72353359)

Obsidian Version: 1.3.5

**Comment by fbob** [comment]
Ouch .. How do you activate the keyboard ?
It seems invisible for me :
![image](https://github.com/danzilberdan/obsidian-mathlive/assets/8211124/a1860021-b6ac-4e23-942e-b5ad98279aca)

Obsidian on linux

**Comment by mofoni** [comment]
> Ouch .. How do you activate the keyboard ? It seems invisible for me : ![image](https://user-images.githubusercontent.com/8211124/244777882-a1860021-b6ac-4e23-942e-b5ad98279aca.png)
> 
> Obsidian 1.3.5 on linux

i start the plugin with CTRL + P and entering the command.

This time with a larger Screenshot:

![image](https://github.com/danzilberdan/obsidian-mathlive/assets/96438242/a86638f3-5693-45b3-925f-fc5577d7ed3d)

**Comment by mofoni** [comment]
the keyboard opens at the same time as the editor in your screenshot.

Here a larger screenshot:


![image](https://github.com/danzilberdan/obsidian-mathlive/assets/96438242/e01442f9-e075-47a6-9232-2bf38e957361)

**Comment by fbob** [comment]
Thanks, @mofoni, for your feedback.
Hmm  it does not seem to work like this for me :

![image](https://github.com/danzilberdan/obsidian-mathlive/assets/8211124/3e927b0b-b346-44d3-9367-c78309e39714)

Or... I'm completely dumb (highly possible)

**Comment by MatlabRes** [comment]
> Thanks, @mofoni, for your feedback. Hmm it does not seem to work like this for me :
> 
> ![image](https://user-images.githubusercontent.com/8211124/246627658-3e927b0b-b346-44d3-9367-c78309e39714.png)
> 
> Or... I'm completely dumb (highly possible)

By default no keyboard too

I'm do

```
cd .obsidian/plugins
git clone https://github.com/danzilberdan/obsidian-mathlive.git
mv obsidian-mathlive mathlive
```

Then in package.json change version mathlive to
```
	"dependencies": {
		"mathlive": "^0.95.0"
	}
```

In main.ts  86 row
simple to this

```const mfe = new MathfieldElement();```

than 
```
npm i
npm run build  
```

![изображение](https://github.com/danzilberdan/obsidian-mathlive/assets/22655314/e8458f10-80a4-4984-9e0c-9aa6816a395a)

**Comment by danzilberdan** [comment]
I will implement this fix asap. Thanks for the help!

**Comment by danzilberdan** [comment]
I just published the fix.
Let me know if there are more issues.

**Comment by MatlabRes** [comment]
Thank you. 

But new css not compared with my obsidian / theme.
So I'm fix a bit.

![изображение](https://github.com/danzilberdan/obsidian-mathlive/assets/22655314/18975021-40d6-4afc-b9a0-cf65e8e41792)


```css
:root {
  --selection-background-color: rgba(0,0,0,0.5);
  --selection-color: green;
  --highlight-text: green;
  --contains-highlight-background-color: rgba(0,0,0,0.5);;
}


.mathlive-modal-content {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: end;
  padding-top: 1rem;
}

math-field {
  font-size: 2rem;
  width: 100%;
  overflow: hidden;
  border-radius: 15px 15px 0 0;
}

.submit {
  background-color: green !important;
  font-weight: bold;
  color: white;
  height: 100%;
  width: 100%;
  height: 2rem;
  margin-top:1px;
  border-radius: 0 0 15px 15px;
}
```

I'm think it may help somebody.
